[package]
name = "rsm-raft"
version = "0.1.0"
authors = ["Unreal Hoang <unrealhoang@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
crossbeam = "*"
rand = "*"
rand_core = "*"
env_logger = "*"
